---
abstract: 'RT-Extension-QuickAssign Extension'
author:
  - 'NETWAYS GmbH <lt>support@netways.de<gt>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.19'
license: gpl_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-QuickAssign
no_index:
  directory:
    - html
    - inc
    - static
requires:
  perl: 5.10.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://git.netways.org/rt4/rt-extension-quickassign
version: 1.0.0
x_module_install_rtx_version: '0.40'
x_requires_rt: 4.4.2
